### ISSUE TITLE
Export data log to SD card

### ISSUE THREAD

**Issue by yw5aj** [kevinfodor/my-sensors#9]
Hi Kevin,

Thank you for the great app! I have a feature request: would it be possible to make it log sensor output data to the SD card, such as in a `csv` format?

Shawn

**Comment by kevinfodor** [comment]
Thanks for the feedback.

That sounds interesting. I think it would be pretty easy to do. There is already some amount of logging to the Android ADB port I would think that could be adapted to some .csv type file on the storage of the device.

Let me look into it and see what I can do. I assume an auto create file (such as current date/time) would be a good approach. Stored to the application folder.  A more advanced feature might allow selection of a file name and/or location.

**Comment by kevinfodor** [comment]
I have added a new logging feature which will write each sensor's event data to a Comma Separated Variable (CSV) file on your device. The logged files (when enable via the 'Start Logging' button) will have an automatically generated file name in the form:

MySensors_&lt;sensor#&gt;\_&lt;sensor type&gt;\_&lt;yyyymmdd>&gt;\_&lt;hhmmss&gt;.csv

For instance: MySensors_2_Gyroscope_20160110_161905.csv
Would be a Gyroscope log (sensor #2 on this device) collected on January 10th, 2016 at 4:19:05 pm

Sample file output looks like this in Excel:

![image](https://cloud.githubusercontent.com/assets/1150846/12224503/6122ae80-b7b8-11e5-894d-ccc4f6ac3284.png)
